services:
  - type: web
    name: asu-hostelcare
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./hostelcare.db
